# Generated by Django 6.0.6 on 2026-06-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_discovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.category'),
        ),
    ]
