# Generated by Django 6.0.6 on 2026-06-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_discovery_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='discovery',
            options={'verbose_name_plural': 'Discoveries'},
        ),
    ]
