# Generated by Django 6.0.6 on 2026-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_tag_discovery_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='discovery_images/'),
        ),
    ]
